server:
  port: 8080
  servlet:
    context-path: /simplewebapp
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    database: postgresql
  sql:
    init:
      data-locations: classpath*:data111.sql
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/employeedb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 3784