server:
  port: 8080
  servlet:
    context-path: /simplewebapp
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
    database: postgresql
    generate-ddl: false
  sql:
    init:
#      data-locations: classpath*:data111.sql
      mode: always
  flyway:
    enabled: true
#    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/employeedb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 3784